version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: "main"
    open-pull-requests-limit: 10
    versioning-strategy: widen
    labels:
      - "npm"
      - "dependencies"
    commit-message:
      prefix: "npm"
    pull-request-branch-name:
      separator: "-"
